---
title: "compare_four_models"
author: "Hui Xin Ng"
date: "2023-03-19"
output: html_document
---

```{r setup, include=FALSE}
libraries <- c("dplyr", "tidyverse", "DescTools", "ggplot2", "readxl", "lme4"
               , "ModelMetrics", "merTools", "lmtest", "emmeans", "haven", "lmerTest"
               , "metaforest", "rstatix", "labelled", "data.table", 'irr')

lapply(libraries, require , character.only = TRUE)

```

 
```{r cars}
#cnn_df <- read.csv("../data_original/wood_2022_brainage.csv")

path = file.path("../data_original/Master_BAI_080720_with_051517completers_060117imagingmaster_genotypes_brainages_ENIGMA_FS_MERGEFK_30122020.sav")

original_df = read_sav(path)
original_df <- original_df %>% dplyr::select("trnsctrw", "cwiisnrs","cwiisis", "cwiicns","fsrp5","stdyptid", 'visit', 'dxgroupFK', 'agevisit') %>% filter(!is.na(trnsctrw)|!is.na(fsrp5)) %>% arrange(stdyptid)
original_df <- setDT(original_df)[, lapply(.SD, na.omit), by = stdyptid]
 
```

```{r}
#df<-read.csv("../data_original/master_bai_merge_cnn_brainage.csv") # this file is created from the Jupyter notebook to produce the same 44 BD and 73 HC participants for analyses 
df<-read.csv("../data_processed/df_all_brainage_2025.csv") 

df %>% group_by(dxgroupFK) %>%tally()
df

```

```{r}
  
 
 
df  <- df %>% mutate(Age2 = agevisit**2, Age3 = agevisit**3, 
                     bpad_ridge = ridge_BrainAge - agevisit,
                     bpad_photon = age_prediction - agevisit,
                     bpad_BrainAgeR = ageprediction_BrainAgeR - agevisit,
                     bpad_cnn = cnn_BrainAge - agevisit)
 
 df
```

### Histogram of bpad across algorithms
```{r}
# ---- Distribution and Normality Test of Brain Predicted Age Difference ----- 
ggplot(df, aes(x=bpad_ridge)) + # non-normal
geom_histogram()+ theme_classic()
shapiro.test(df$bpad_ridge)

ggplot(df, aes(x=bpad_BrainAgeR)) + 
  geom_histogram() + theme_classic()
shapiro.test(df$bpad_BrainAgeR)

ggplot(df, aes(x=bpad_photon)) + 
  geom_histogram() + theme_classic()
shapiro.test(df$bpad_photon)

ggplot(df, aes(x=bpad_cnn)) + 
  geom_histogram() + theme_classic()
shapiro.test(df$bpad_cnn)

# ---- Distribution and Normality Test of Brain Age ----- 
ggplot(df, aes(x=ridge_BrainAge)) + 
geom_histogram()+ theme_classic()
shapiro.test(df$ridge_BrainAge)

ggplot(df, aes(x=ageprediction_BrainAgeR)) + 
  geom_histogram() + theme_classic()
shapiro.test(df$ageprediction_BrainAgeR)

ggplot(df, aes(x=age_prediction)) + 
  geom_histogram() + theme_classic()
shapiro.test(df$age_prediction)

ggplot(df, aes(x=cnn_BrainAge)) +   # non-normal
  geom_histogram() + theme_classic()
shapiro.test(df$cnn_BrainAge)

# Function to filter out data points outside of 3 SDs
filter_outliers <- function(x) {
  sd_x <- sd(x)
  mean_x <- mean(x)
  upper_limit <- mean_x + 3 * sd_x
  lower_limit <- mean_x - 3 * sd_x
  return(between(x, lower_limit, upper_limit))
}

df <- df %>%  
  filter(filter_outliers(bpad_ridge),
         filter_outliers(bpad_BrainAgeR),
         filter_outliers(bpad_photon),
         filter_outliers(bpad_cnn)) 

# correlation between chronological age and brain-pad
df %>% dplyr::select(bpad_ridge, bpad_photon , bpad_BrainAgeR ,bpad_cnn, dxgroupFK, gender, agevisit) %>%  melt(id = c('agevisit', 'dxgroupFK', 'gender'))%>% group_by(variable, dxgroupFK) %>% summarise(pval = as.numeric(cor.test(agevisit, value)[3]),                                                                correlation = cor(agevisit, value))%>% mutate(pval = round(pval, 3), correlation = round(correlation, 3))

# correlation between chronological age and predicted age
df %>% dplyr::select(ridge_BrainAge, ageprediction_BrainAgeR , age_prediction ,cnn_BrainAge, dxgroupFK, gender, agevisit) %>%  melt(id = c('agevisit', 'dxgroupFK', 'gender'))%>% group_by(variable, dxgroupFK) %>% summarise(pval = as.numeric(cor.test(agevisit, value)[3]),  correlation = cor(agevisit, value))%>% mutate(pval = round(pval, 3), correlation = round(correlation, 3)) %>% filter()

pairs_braingage <- list(c("ridge_BrainAge", "ageprediction_BrainAgeR"),
              c("ridge_BrainAge", "age_prediction"),
              c("ridge_BrainAge", "cnn_BrainAge"),
              c("ageprediction_BrainAgeR", "age_prediction"),
              c("ageprediction_BrainAgeR", "cnn_BrainAge"),
              c("age_prediction", "cnn_BrainAge"))

pairs_bpad <- list(
  c("bpad_ridge", "bpad_photon"),
  c("bpad_ridge", "bpad_BrainAgeR"),
  c("bpad_ridge", "bpad_cnn"),
  c("bpad_photon", "bpad_BrainAgeR"),
  c("bpad_photon", "bpad_cnn"),
  c("bpad_BrainAgeR", "bpad_cnn"))

# Function to calculate ICC for each pair
calculate_ICC <- function(pair, group_label) {
  ICC_result <- df %>% filter(dxgroupFK == group_label) %>%
    select_all(all_of(pair)) %>%
    DescTools::ICC(.)
  return(ICC_result)
}


getICC <- function(pairs, g) {
# Apply the function to each pair and store results in a list
ICC_results <- lapply(pairs, function(p) calculate_ICC(p, g))

ICC2 <- c()
names(ICC_results) <- sapply(pairs, paste, collapse = "_vs_")
names(ICC_results)
for (i in seq_along(ICC_results)) {
  ICC_row2 <- ICC_results[[i]]$results[2,]
 
ICC2 <- rbind(ICC_row2, ICC2)
}

ICC2 <- cbind(names(ICC_results), ICC2)  
  return (ICC2)
}


#  Brain-PAD is less variable than Predicted brain age because the spread is smaller
# # So if we split the sample into BD vs. HC, then we expect that BD has higher correlation
# # among each other, and HC has lower correlation, because BD might have a wider spread than HC
# 
# # This shows the agreement among the models in terms of the deviation from chronological age in terms of
# getICC(pairs_bpad, 'HC') %>% mutate(est = round(est, 2))
# 
# # this shows the agreement among the predicted ages across the models
# # high ICC shows that the predicted ages from a given pair of models are similar to each other
# # low ICC suggest there is variability in the predicted ages. 
# getICC(pairs_braingage, 'HC') %>% mutate(est = round(est, 2))
# 
# 
# getICC(pairs_bpad, 'BD') %>% mutate(est = round(est, 2))
# getICC(pairs_braingage, 'BD') %>% mutate(est = round(est, 2))

```

```{r}
# --- Correlation Matrix BPAD ---- 
# Select the columns you want to calculate pairwise correlations 
cor_data <-  df[, c("bpad_ridge", "bpad_photon", "bpad_BrainAgeR", "bpad_cnn")]
# Calculate pairwise correlations
correlation_matrix <- cor(cor_data)

# Print correlation matrix
round(correlation_matrix, 3)

# --- Correlation Matrix Brain Age ---- 
# Select the columns you want to calculate pairwise correlations for
cor_data <-  df[, c("ridge_BrainAge", "age_prediction", "ageprediction_BrainAgeR", "cnn_BrainAge")]

# Calculate pairwise correlations
correlation_matrix <- cor(cor_data)

# Print correlation matrix
round(correlation_matrix, 3)
```

### Correlation between age and predicted age for all 4 models; seperate plots by group and separate lines by sex
```{r }
splot_titles <- c(ridge_BrainAge = 'Multimodal', age_prediction = 'PHOTON', ageprediction_BrainAgeR =  'BrainageR', cnn_BrainAge = 'DenseNet', `0` = 'HC', `1` = 'BD')

 

df %>% dplyr::select(ridge_BrainAge, age_prediction, ageprediction_BrainAgeR , cnn_BrainAge , dxgroupFK, gender, agevisit) %>%  melt(id = c('agevisit', 'dxgroupFK', 'gender')) %>%
  ggplot(aes(x = agevisit, y = value , color = factor(gender))) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +  # Add a linear regression line
  labs(x = "Chronological Age", y = "Predicted Brain Age") +
  theme_minimal() +
  facet_grid(~ variable + dxgroupFK, label = as_labeller(splot_titles)) +  
  geom_text(
    data = . %>% group_by(variable,dxgroupFK) %>% summarise(correlation = cor(agevisit, value, use = "complete.obs" , method = "pearson")),
    aes(x = Inf, y = -Inf, label = paste("r = ", round(correlation, 2)) ),
    hjust = 1, vjust = -1,
    color = "black"
  ) + #s and add annotations
  geom_text(
    data = . %>% group_by(variable,dxgroupFK) %>% summarise(pval = as.numeric(cor.test(agevisit, value)[3])),
    aes(x = Inf, y = -Inf, label =sprintf("p = %.2e", pval)),
    hjust = 1, vjust = 0,
    color = "black"
  ) 
ggsave(filename = "figures/predictedage_corr_age.jpeg"  ,dpi = 500, width = 12, height = 3)
dev.off()

```
### Correlation between age and uncorrected brain-PAD for all 4 models 
```{r}
splot_titles <- c(bpad_ridge = 'Multimodal', bpad_photon = 'PHOTON', bpad_BrainAgeR =  'BrainageR', bpad_cnn = 'DenseNet',  `0` = 'HC',`1` = 'BD')

df %>% dplyr::select(bpad_ridge, bpad_photon , bpad_BrainAgeR ,bpad_cnn, dxgroupFK, gender, agevisit) %>%  melt(id = c('agevisit', 'dxgroupFK', 'gender')) %>%
  ggplot(aes(x = agevisit, y = value )) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +  # Add a linear regression line
  labs(x = "Chronological Age", y = "Uncorrected Brain-PAD") +
  theme_minimal() +
  facet_grid(~ variable , labeller = as_labeller(splot_titles)) + #s and add annotations
  geom_text(
    data = . %>% group_by(variable) %>% summarise(correlation = cor(agevisit, value, use = "complete.obs", method = "pearson")),
    aes(x = Inf, y = -Inf, label = paste("r =", round(correlation, 2)) ),
    hjust = 1, vjust = -1,
    color = "black"
  )  + #s and add annotations
  geom_text(
    data = . %>% group_by(variable) %>% summarise(pval = as.numeric(cor.test(agevisit, value)[3])),
    aes(x = Inf, y = -Inf,  label =sprintf("p = %.2e", pval)),
    hjust = 1, vjust = 0,
    color = "black"
  )   
ggsave("figures/uncorrected_bpad_corr_age.jpeg",dpi = 500, width = 12, height = 3)
dev.off()
```

### Correlation between age and uncorrected brain-PAD for all 4 models; seperate plots by group, separate lines by sex
```{r fig.align="center", echo = FALSE,fig.width = 12, fig.height=6}
splot_titles <- c(bpad_ridge = 'Multimodal', bpad_photon = 'PHOTON', bpad_BrainAgeR =  'BrainageR', bpad_cnn = 'DenseNet',  `0` = 'HC',  `1` = 'BD')
df %>% dplyr::select(bpad_ridge, bpad_photon , bpad_BrainAgeR ,bpad_cnn, dxgroupFK, gender, agevisit) %>%  melt(id = c('agevisit', 'dxgroupFK', 'gender')) %>%
  ggplot(aes(x = agevisit, y = value , color = factor(gender))) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +  # Add a linear regression line
  labs(x = "Chronological Age", y = "Uncorrected Brain-PAD") +
  theme_minimal() +
  facet_grid(~ variable + dxgroupFK, labeller = as_labeller(splot_titles)) + #s and add annotations
  geom_text(
    data = . %>% group_by(variable,dxgroupFK) %>% summarise(correlation = cor(agevisit, value, use = "complete.obs", method = "pearson")),
    aes(x = Inf, y = -Inf, label = paste("r =", round(correlation, 2)) ),
    hjust= 1, vjust = -1,
    color = "black"
  )  + #s and add annotations
  geom_text(
    data = . %>% group_by(variable,dxgroupFK) %>% summarise(pval = as.numeric(cor.test(agevisit, value)[3])),
    aes(x = Inf, y = -Inf, label =sprintf("p = %.2e", pval)),
    hjust = 1, vjust = 0,
    color = "black"
  )   
ggsave("figures/bpadresid_corr_age_bysexdx.jpeg",dpi = 500, width = 12, height = 3)
dev.off()
 
```
